version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "5433:5433"
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - ./Backend/.env
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./Backend:/app  
      - /app/node_modules  

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      - app-network
    volumes:
      - ./Frontend:/app 
      - /app/node_modules  

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: networksupport
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Asia/Jakarta
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge
